### PR TITLE
New York Times Clone Ready

### PR DESCRIPTION
**Pull request by Dandush03**
We made a mimics page of an article from the New York Times Magazine

We followed the instruction and formatted all of the page elements with float positioning and we run a bugs check with Sticklers.

We only used HTML file and CSS file

By:
Abdel Pérez
Daniel Laloush

### CODE REVIEW

**Review by rOluochKe — COMMENTED** [review]
### Under review...

**Review by rOluochKe — CHANGES_REQUESTED** [review]
@Dandush03 and @abdelp 
### Good job, this is impressive what you have done. However, there are a few changes you need to make for your project to be approved. You did really well.
- Change document encoding type from UFF-8 to UTF-8 and validate your code on [html5 validator](https://validator.w3.org/#validate_by_upload)
- In your CSS avoid using the keyword **!important**

### Once you have made all these changes, resubmit for a another review. All the best in your next submission

**Comment by Dandush03** [comment]
### Hello! Again!

we manage to fix all the bugs listed, we are just missing 1 that is taking out the scrolling property from the iframe, but the overflow property in Chrome and Safari are not supported yet, so we are using both, in CSS and in the HTML file. hope it won't be an issue.

regards!

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi team, good job :clap:. A few more changes are required:**
1. The New York Times logo should be a link.
2. There is a fixed footer on the original page, include it in your own project.
image
3. Edit your pull request title to something descriptive about the pull request - (maybe New York Times Clone Ready) 

Kindly make these changes and submit another code review request.

**Cheers**

**Status: Changes requested**

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Hi team, you have not made any change since the previous review,**
Please effect the required changes and submit another code review request.

**Status: Changes requested**

**Comment by Dandush03** [comment]
Thanks for your review already fixed all issues. 
Thanks for your time

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**Good work @Dandush03, @abdelp. :trophy:Your project is approved!**

You have one new html validation error coming up as a result of your adjustments. I trust that you will fix it before you merge to master.

**Happy coding:smile:**

**Status: Approved.**

**Pull request merged**
