### PR TITLE
Finished 3rd Microverse Project - Branch: Development

### PR DESCRIPTION
**Pull request by Dandush03**
We made a mimics page of an article from New York Times Magazine

We fallowed the instruction and formatted all of the page element with float positioning and we run a bugs check with Sticklers.

We only used HTML file and CSS file

By:
Abdel Pérez
Daniel Laloush

### CODE REVIEW

**Comment by Dandush03** [comment]
We made a mimics page of an article from the New York Times Magazine

We followed the instruction and formatted all of the page elements with float positioning and we run a bugs check with Sticklers.

We only used HTML file and CSS file

By:
Abdel Pérez
Daniel Laloush

**Comment by Dandush03** [comment]
Still Waiting for code review

**Comment by Dandush03** [comment]
We made a mimics page of an article from the New York Times Magazine

We followed the instruction and formatted all of the page elements with float positioning and we run a bugs check with Sticklers.

We only used HTML file and CSS file

By:
Abdel Pérez
Daniel Laloush

**Review by rOluochKe — COMMENTED** [review]
### Under review....

**Pull request closed without merging**
